version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs: 
  build: 
    docker:       
      - image: circleci/node:12.13.1    
    working_directory: ~/repo
    steps:      
      - checkout
      - run: npm cache clean --force
      - run: npm install
      - run: CI=false npm run build
      - run:
          name: git conf
          command: |
            git config --global user.email "slimani.ibr@gmail.com"
            git config --global user.name "brahim-slimani"
      - add_ssh_keys:
          fingerprints:
            - "65:bf:37:cf:8e:8c:1b:e1:9a:68:c0:1c:a6:82:92:f6"
      - run: npm run deploy